using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using EgorLin.Keys.Backend.Indexers.Collection;
using UnityEditor;
using UnityEngine;

namespace EgorLin.Keys.Editor.CodeGeneration
{
	public static class KeyCollectionCodeGenerator
	{
		[MenuItem("Tools/Keys/Generate Code")]
		public static void Generate()
		{
			var settings = KeyCollectionCodeGeneratorSettings.GetOrCreate();
			
			if (string.IsNullOrEmpty(settings.OutputFolder))
			{
				Debug.LogError("Output folder is not set in KeyCollectionCodeGeneratorSettings");
				return;
			}
			
			if (string.IsNullOrEmpty(settings.ClassName))
			{
				Debug.LogError("Class name is not set in KeyCollectionCodeGeneratorSettings");
				return;
			}
			
			EnsureOutputFolderExists(settings.OutputFolder);
			
			var collections = LoadAllKeyCollections();
			var groupedByFirstPath = GroupCollectionsByFirstPath(collections);
			
			CleanupOldFiles(settings.OutputFolder, settings.ClassName);
			
			foreach (var group in groupedByFirstPath)
			{
				GeneratePartialClass(settings, group.Key, group.Value);
			}
			
			AssetDatabase.Refresh();
			
			Debug.Log($"Generated {groupedByFirstPath.Count} key files in {settings.OutputFolder}");
		}
		
		private static void EnsureOutputFolderExists(string folderPath)
		{
			if (!AssetDatabase.IsValidFolder(folderPath))
			{
				var folders = folderPath.Split('/');
				var currentPath = folders[0];
				
				for (int i = 1; i < folders.Length; i++)
				{
					var nextPath = $"{currentPath}/{folders[i]}";
					
					if (!AssetDatabase.IsValidFolder(nextPath))
					{
						AssetDatabase.CreateFolder(currentPath, folders[i]);
					}
					
					currentPath = nextPath;
				}
			}
		}
		
		private static List<KeyCollectionData> LoadAllKeyCollections()
		{
			var collections = KeyCollectionOwnerIndexer.GetAllAssets();
			var result = new List<KeyCollectionData>();
			
			foreach (var collection in collections)
			{
				foreach (var keyValue in collection.GetAllKeys())
				{
					var pathParts = new List<string>();
					
					foreach (var pathNode in collection.GetAllPaths())
					{
						var tag = pathNode.Value;
						
						if (!pathNode.IsEmpty())
						{
							pathParts.Add(tag);
						}
					}
					
					if (!keyValue.IsEmpty())
					{
						result.Add(new KeyCollectionData
						{
							PathParts = pathParts,
							KeyName = keyValue.Value,
							KeyHash = keyValue.Id.Hash
						});
					}
				}
			}
			
			return result;
		}
		
		private static Dictionary<string, List<KeyCollectionData>> GroupCollectionsByFirstPath(List<KeyCollectionData> collections)
		{
			var grouped = new Dictionary<string, List<KeyCollectionData>>();
			
			foreach (var collection in collections)
			{
				var firstPath = collection.PathParts.Count > 0 
					? collection.PathParts[0] 
					: "Root";
				
				if (!grouped.ContainsKey(firstPath))
				{
					grouped[firstPath] = new List<KeyCollectionData>();
				}
				
				grouped[firstPath].Add(collection);
			}
			
			return grouped;
		}
		
		private static void CleanupOldFiles(string outputFolder, string className)
		{
			var files = Directory.GetFiles(outputFolder, $"{className}.*.cs");
			
			foreach (var file in files)
			{
				File.Delete(file);
			}
		}
		
		private static void GeneratePartialClass(KeyCollectionCodeGeneratorSettings settings, string groupName, List<KeyCollectionData> collections)
		{
			var builder = new System.Text.StringBuilder();
			
			// Header
			builder.AppendLine("// This file is auto-generated. Do not modify manually.");
			builder.AppendLine("// Generated by KeyCollectionCodeGenerator");
			builder.AppendLine();
			
			// Namespace KeyId
			if (!string.IsNullOrEmpty(settings.NamespaceKeyId))
			{
				builder.AppendLine($"using {settings.NamespaceKeyId};");
				builder.AppendLine();
			}
			
			// Namespace
			if (!string.IsNullOrEmpty(settings.Namespace))
			{
				builder.AppendLine($"namespace {settings.Namespace}");
				builder.AppendLine("{");
			}
			
			// Class
			var indent = !string.IsNullOrEmpty(settings.Namespace) ? "\t" : "";
			builder.AppendLine($"{indent}public static partial class {settings.ClassName}");
			builder.AppendLine($"{indent}{{");
			
			GenerateKeys(collections, builder, indent);

			builder.AppendLine($"{indent}}}");
			
			// Close namespace
			if (!string.IsNullOrEmpty(settings.Namespace))
			{
				builder.AppendLine("}");
			}
			
			// Write file
			var sanitizedGroupName = SanitizeFileName(groupName);
			var fileName = $"{settings.ClassName}.{sanitizedGroupName}.cs";
			var filePath = Path.Combine(settings.OutputFolder, fileName);
			
			File.WriteAllText(filePath, builder.ToString());
		}

		private static void GenerateKeys(List<KeyCollectionData> collections, StringBuilder builder, string indent)
		{
			// Generate keys grouped by full path
			var groupedByPath = collections
				.GroupBy(c => string.Join("/", c.PathParts))
				.OrderBy(g => g.Key);
			
			bool isFirstGroup = true;
			
			foreach (var pathGroup in groupedByPath)
			{
				// Add spacing between different path groups
				if (!isFirstGroup)
				{
					builder.AppendLine();
				}
				isFirstGroup = false;
				
				// Add path comment
				if (!string.IsNullOrEmpty(pathGroup.Key))
				{
					builder.AppendLine($"{indent}\t// {pathGroup.Key}");
				}
				
				// Generate keys in this path
				foreach (var collection in pathGroup.OrderBy(c => c.KeyName))
				{
					var fieldName = GenerateFieldName(collection);
					builder.AppendLine($"{indent}\tpublic static readonly KeyId {fieldName} = KeyId.Create({collection.KeyHash});");
				}
			}
		}

		private static string GenerateFieldName(KeyCollectionData collection)
		{
			var parts = new List<string>(collection.PathParts) { collection.KeyName };

			// Convert to PascalCase and remove invalid characters
			var fieldName = string.Join("_", parts.Select(SanitizeIdentifier));
			
			return fieldName;
		}
		
		private static string SanitizeIdentifier(string input)
		{
			if (string.IsNullOrEmpty(input))
			{
				return "Invalid";
			}
			
			// Replace spaces and special characters with underscores
			var sanitized = System.Text.RegularExpressions.Regex.Replace(input, @"[^a-zA-Z0-9_]", "_");
			
			// Ensure it starts with a letter or underscore
			if (char.IsDigit(sanitized[0]))
			{
				sanitized = "_" + sanitized;
			}
			
			// Convert to PascalCase
			return ToPascalCase(sanitized);
		}
		
		private static string ToPascalCase(string input)
		{
			if (string.IsNullOrEmpty(input))
			{
				return input;
			}
			
			var parts = input.Split('_');
			var result = new System.Text.StringBuilder();
			
			foreach (var part in parts)
			{
				if (string.IsNullOrEmpty(part))
				{
					continue;
				}
				
				result.Append(char.ToUpper(part[0]));
				if (part.Length > 1)
				{
					result.Append(part.Substring(1));
				}
			}
			
			return result.ToString();
		}
		
		private static string SanitizeFileName(string input)
		{
			// Remove invalid file name characters
			var invalid = Path.GetInvalidFileNameChars();
			var sanitized = string.Join("_", input.Split(invalid, StringSplitOptions.RemoveEmptyEntries));
			
			return string.IsNullOrEmpty(sanitized) ? "Root" : sanitized;
		}
		
		private class KeyCollectionData
		{
			public List<string> PathParts;
			public string KeyName;
			public int KeyHash;
		}
	}
}